[package]
name = "objc-uikit-impl"
version = "0.0.0"
authors = ["Steven Sheldon"]

build = "build.rs"

[dependencies]
objc = "0.1"
objc-foundation = "0.0"

[dependencies.objc-uikit]
path = ".."

[build-dependencies]
gcc = "0.3"
