[package]
name = "uikit-example"
version = "0.0.0"
authors = ["Steven Sheldon"]

[lib]
name = "uikit_example"
crate-type = ["staticlib"]

[dependencies]
objc-foundation = "0.0"

[dependencies.objc-uikit]
path = "../.."

[dependencies.objc-uikit-impl]
path = "../../impl"
